version: '3.8'

services:
  python-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "4200:4200"
    environment:
      - PYTHONPATH=/workspace
      - PREFECT_UI_URL=http://localhost:4200