name: CI

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Install dependencies
        run: uv sync --extra dev
        
      - name: Run pre-commit
        run: uv run pre-commit run --all-files
        
      - name: Upload coverage
        run: uv run pytest --cov=python_devcontainer_template --cov-report=xml --cov-fail-under=95